### PR TITLE
new carbon cycle & climate calibration, remodularised climate

### PR DESCRIPTION
**Pull request by chrisdwells**
Connected the ocean carbon cycle to the atmosphere side and deleted old atmospheric carbon cycle.
Updated the climate calibration members including selected climate case and external sensi cases.
Remodularised Climate.
Updated Total global SLR name in calibration file.

### CODE REVIEW

**Comment by chrisdwells** [comment]
The reason Energy is in there is because when I remodularised it broke an STA link somehow, so I had to add it back in. This can probably be removed and then fixed if necessary in the conflicting one. Wasn't sure if I should include isdb.

**Comment by lnnrtrmm** [comment]
Just pushed a new commit with the newly connected carbon cycle. There now seems to be the problem that biofuels produce quite large CO2 emissions, due to the new calculation:
image
I assume that the variable "UNIT GtC per PCal crop" could be recalibrated? Biofuel emissions now seem to be almost as big as those from other energy sources:
image
Much larger than in the previous calculation
image
@BenjaminBlanz , @jnnsbrr , @rj1971350

**Comment by lnnrtrmm** [comment]
I think that is in some sense true, as the amount of carbon that is eventually outgassed in the engine is not the amount of carbon that is originally in the plant on the field (i.e. before applying the harvest index). BUT it is probably also not the amount of carbon that is harvested (i.e. after applying the harvest index), as there will be a lot of leftover carbon on the way to the fuel, is my guess.

Therefore, I think Ben's original implementation actually made more sense, when we want to get only the emissions from burning the biofuel. We can probably ignore all the leftover carbon here, as the "net land carbon flux"  (now correctly implemented, see previous commit) takes care that we don't loose carbon on the way anywhere.

**Comment by rj1971350** [comment]
@lnnrtrmm excellent -- now if you were to delete the badly formed variable "CO2 emissions from Food and Land Use" (and its causers) and if the others agree put back @BenjaminBlanz's "carbon intensity of biofuels" this PR would be ready? (I will take care of the merge conflict when you tell me to)

**Comment by BenjaminBlanz** [comment]
In general I would advocate for having specific emissions variables as possible as that will help us with tracing and communicating effects of policies.

**Pull request merged**
