### PR TITLE
closing feedback for climate impacts on Labour prod

### PR DESCRIPTION
**Pull request by BenjaminBlanz**
Based on two discussion with Martin. We found that in the current version of frida having a change in labour prod affect the desired additional hires (to offset the lost productivity) is the best way forward. In a future version of frida, we will want to include effects of production being restructured to use more capital instead of labour, if labour becomes less productive. The current approach instead assumes that more money is spent on labour to hire additional labourers to offset the lost production by each of them.

### CODE REVIEW

**Comment by wasbridge** [comment]
I don't see a problem with your guys' approach in the short term esp if we document the assumption that reduced labor productivity is amelorated with more labor.  With that said if we want it to impact capital, we would feed it into investment as something that raised the indicated bank investment growth rate at the margins.  the idea being that if investors notice an oppertunity (poorly performing labor) they'll be spurred to invest more to gain the rewards from correcting the issue.  This would then create more "capital" as a result

**Comment by BenjaminBlanz** [comment]
I think we can merge this and put the capital shifting impacts as a todo for when wealth and capital are being worked on

**Comment by wasbridge** [comment]
Agreed.  Will handle this Tuesday when I return from vacation

**Comment by wasbridge** [comment]
This is abandoned b/c productivity will be included in martin's updated economny (offline pull request) which will obviate the need for this

**Pull request closed without merging**
