### PR TITLE
Modularized and tagged energy

### PR DESCRIPTION
**Pull request by BenjaminBlanz**
Modularized and tagged energy. May cause an error in economy due to changes in location of variables. Fix to economy not included in pull request to avoid conflicts.

### CODE REVIEW

**Comment by wasbridge** [comment]
Include the econ fix.  We never want a broken model committed.

You'll also need to fix the references to variables in the /Data folder.
Fix CalibrationData.csv, uncertainty_parameters.csv and external_sensi.csv

**Comment by wasbridge** [comment]
Variable names never double stack modules...

i.e. don't do energy.other.XXX just do other.XXX. 

You'll know you did it right b/c you'll be able to re-import the calibration data without error.  Model > Data Manager, Load external data from run.

**Comment by BenjaminBlanz** [comment]
the import of the calibration data was happy like this though. If we drop energy. we should rename other to something more intuitive. Otherwise going through the data other could refer to anything.

**Comment by wasbridge** [comment]
Yes -- rename other to be Other Energy of the equivalent.

Billy

**Comment by BenjaminBlanz** [comment]
Ok, changed the module names, removed the multilevel references from data file, included all files. Runs are error free. Import reports one error for Finance.investmetns though, but I consider that a seperate issue.

**Comment by wasbridge** [comment]
@BenjaminBlanz - you may want to rebase your changes ontop of the new main.  I merged in the changes from Jannes and Chris Wells on Food & Land Use and Climate.  The easiest way to do this is to save a copy of your current model, and replace the old energy module with your new energy module.  Then before opening it in Stella you can go through FRIDA.stmx in a text editor and replace Energy. with the name of the new module which contains that variable.

**Comment by BenjaminBlanz** [comment]
@wasbridge please have a look now. The list of calibration variables got borked but otherwise this should be correct now. I think I managed to not break the changes to landuse and climate during the rebase please verify.

**Pull request merged**
