### PR TITLE
Bio Energy and CCS

### PR DESCRIPTION
**Pull request by BenjaminBlanz**
draft pull req, preceding calibration

### CODE REVIEW

**Comment by BenjaminBlanz** [comment]
before merging> disconnect again from crop demand, then get quanties calibrated

**Comment by BenjaminBlanz** [comment]
am rebasing to current mainline frida

**Comment by BenjaminBlanz** [comment]
Energy module file should now be ok to overwrite existing mainline

**Comment by BenjaminBlanz** [comment]
After mainline I will add emissions to biofuels

**Comment by wasbridge** [comment]
This is not mergeable -- I cannot recover this.  You'll have to copy and paste the specific changes you made into a new branch made off of the current root.  You have too many self conflicts that I just cannot figure out

**Comment by BenjaminBlanz** [comment]
Will give it a go

**Comment by wasbridge** [comment]
Hold on -- I think I may have recovered this.

**Comment by BenjaminBlanz** [comment]
made a new branch for merging, based on the current mainline version. Closing this pull req.

**Pull request closed without merging**
