### PR TITLE
Ccd hdd energy demand

### PR DESCRIPTION
**Pull request by BenjaminBlanz**
Chris and I have implemented a new structure for change in energy demand due to change in heating and cooling degree days due to climate change (compared to preindustrial). We provide calibration following to different papers Chris found, documented in the module.

### CODE REVIEW

**Comment by BenjaminBlanz** [comment]
We went with the calib according to Rode et al. as the default, as that paper is newer. This implies an overall reduction in energy demand, the reduction in heating demand is stronger than the increase in cooling demand.

**Comment by BenjaminBlanz** [comment]
In V3 Jeffs behavioural model could influence the uptake of AC and therby the energy demand for cooling. This would add extra structure seperating the energy per actual cooling from the build up of AC. The current parameter conflates both of these effects.

**Comment by wasbridge** [comment]
@BenjaminBlanz @chrisdwells Are you both happy with how I now treat HFFC134a emissions as purely driven by CDD?

**Comment by chrisdwells** [comment]
It's probably good for now cheers - I guess the logistic is to give a saturation due to improving tech? Ultimately we'd like to connect the "Change in energy used for cooling due to climate change in MWh" to emissions. Chris Smith's colleague from IIASA is going to send over data on historical HFC emissions from this source to aid with that, but that'll be a couple weeks at least so maybe not in for V2.

**Pull request merged**
