### PR TITLE
Endogenous energy investment with PID control

### PR DESCRIPTION
**Pull request by BenjaminBlanz**
based the control off relative deviations in supply vs demand, thereby avoided the cycle I was concerned about in the mattermost card.

A relative supply demand missmatch causes a relative change in energy investment (of all types), 
(P) proportional to the magnitude of the deviation, 
(I) accumula missmatch causes increased adjustment
(D) adjusted for the rate of change in the missmatch over time (faster increasesing missmatch causes increased changes in investments to catch it

### CODE REVIEW

**Comment by wasbridge** [comment]
Have you run this using the Greenness of Policy sensitivity analysis (it
runs 11 different scenarios)?  Are you happy with those results for the
energy balance?

[image: image.png]

**Comment by BenjaminBlanz** [comment]
Just ran it. I think it is generally fine. The runs that have the strongest deviations are the interpolations between the calibrated points 0,0.5,1 . To clean those up we could define more points on the greeness of policy scale with optimised investments. But I would not do that now, as I see the current greeness of policy as a intermediate solution to endogenous preferences. Once those are in I would include a mechanism to endogenously choose the cheapest/appropriatly greeen energy source to invest in. I.e. endogenous energy investments per type, instead of the overall solution we have now.

**Comment by BenjaminBlanz** [comment]
Actually, I did some further tweaking and found some much better control values. one moment

**Comment by BenjaminBlanz** [comment]
image

**Comment by BenjaminBlanz** [comment]
The only concern now would be that this control is "to good". It causes very drastic changes to investments to meet any deviations. Something to discuss at the next energy dev meeting.

**Comment by wasbridge** [comment]
Yes -- something to discuss -- check out investments in Fossil Fuel Extraction capital.  My guess is we'll want to slow the response a bit -- also you'll want to use Society.Policy_Start_Year as the start for the PID controller, not 2020

**Pull request merged**
